[package]
name = "engine_allocator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dlmalloc = "0.2.4"
wasm-bindgen = "0.2.84"
