// AUTO-GENERATED DO NOT EDIT

// taken from https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
export const extensionToMime = (extension: string) => {
    switch (extension) {
		case "3g2":
			return "video/3gpp2"
		case "3gp":
			return "video/3gpp"
		case "7z":
			return "application/x-7z-compressed"
		case "aac":
			return "audio/aac"
		case "abw":
			return "application/x-abiword"
		case "arc":
			return "application/x-freearc"
		case "avi":
			return "video/x-msvideo"
		case "avif":
			return "image/avif"
		case "azw":
			return "application/vnd.amazon.ebook"
		case "bin":
			return "application/octet-stream"
		case "bmp":
			return "image/bmp"
		case "bz":
			return "application/x-bzip"
		case "bz2":
			return "application/x-bzip2"
		case "cda":
			return "application/x-cdf"
		case "csh":
			return "application/x-csh"
		case "css":
			return "text/css"
		case "csv":
			return "text/csv"
		case "doc":
			return "application/msword"
		case "docx":
			return "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
		case "eot":
			return "application/vnd.ms-fontobject"
		case "epub":
			return "application/epub+zip"
		case "gif":
			return "image/gif"
		case "gz":
			return "application/gzip"
		case "htm":
		case "html":
			return "text/html"
		case "ico":
			return "image/vnd.microsoft.icon"
		case "ics":
			return "text/calendar"
		case "jar":
			return "application/java-archive"
		case "jpeg":
		case "jpg":
			return "image/jpeg"
		case "js":
		case "mjs":
			return "application/javascript"
		case "json":
			return "application/json"
		case "jsonld":
			return "application/ld+json"
		case "mid":
		case "midi":
			return "audio/midi"
		case "mp3":
			return "audio/mpeg"
		case "mp4":
			return "video/mp4"
		case "mpeg":
			return "video/mpeg"
		case "mpkg":
			return "application/vnd.apple.installer+xml"
		case "odp":
			return "application/vnd.oasis.opendocument.presentation"
		case "ods":
			return "application/vnd.oasis.opendocument.spreadsheet"
		case "odt":
			return "application/vnd.oasis.opendocument.text"
		case "oga":
			return "audio/ogg"
		case "ogv":
			return "video/ogg"
		case "ogx":
			return "application/ogg"
		case "opus":
			return "audio/opus"
		case "otf":
			return "font/otf"
		case "pdf":
			return "application/pdf"
		case "php":
			return "application/x-httpd-php"
		case "png":
			return "image/png"
		case "ppt":
			return "application/vnd.ms-powerpoint"
		case "pptx":
			return "application/vnd.openxmlformats-officedocument.presentationml.presentation"
		case "rar":
			return "application/vnd.rar"
		case "rtf":
			return "application/rtf"
		case "sh":
			return "application/x-sh"
		case "svg":
			return "image/svg+xml"
		case "tar":
			return "application/x-tar"
		case "tif":
		case "tiff":
			return "image/tiff"
		case "ts":
			return "video/mp2t"
		case "ttf":
			return "font/ttf"
		case "txt":
			return "text/plain"
		case "vsd":
			return "application/vnd.visio"
		case "wasm":
			return "application/wasm"
		case "wav":
			return "audio/wav"
		case "weba":
			return "audio/webm"
		case "webm":
			return "video/webm"
		case "webp":
			return "image/webp"
		case "woff":
			return "font/woff"
		case "woff2":
			return "font/woff2"
		case "xhtml":
			return "application/xhtml+xml"
		case "xls":
			return "application/vnd.ms-excel"
		case "xlsx":
			return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
		case "xml":
			return "application/xml"
		case "xul":
			return "application/vnd.mozilla.xul+xml"
		case "zip":
			return "application/zip"
		default:
            return ""
    }
}

export type FileExtension = (
	"3g2" |
	"3gp" |
	"7z" |
	"aac" |
	"abw" |
	"arc" |
	"avi" |
	"avif" |
	"azw" |
	"bin" |
	"bmp" |
	"bz" |
	"bz2" |
	"cda" |
	"csh" |
	"css" |
	"csv" |
	"doc" |
	"docx" |
	"eot" |
	"epub" |
	"gif" |
	"gz" |
	"htm" |
	"html" |
	"ico" |
	"ics" |
	"jar" |
	"jpeg" |
	"jpg" |
	"js" |
	"json" |
	"jsonld" |
	"mid" |
	"midi" |
	"mjs" |
	"mp3" |
	"mp4" |
	"mpeg" |
	"mpkg" |
	"odp" |
	"ods" |
	"odt" |
	"oga" |
	"ogv" |
	"ogx" |
	"opus" |
	"otf" |
	"pdf" |
	"php" |
	"png" |
	"ppt" |
	"pptx" |
	"rar" |
	"rtf" |
	"sh" |
	"svg" |
	"tar" |
	"tif" |
	"tiff" |
	"ts" |
	"ttf" |
	"txt" |
	"vsd" |
	"wasm" |
	"wav" |
	"weba" |
	"webm" |
	"webp" |
	"woff" |
	"woff2" |
	"xhtml" |
	"xls" |
	"xlsx" |
	"xml" |
	"xul" |
	"zip" 
)

export type Mime = (
	"application/epub+zip" |
	"application/gzip" |
	"application/java-archive" |
	"application/javascript" |
	"application/json" |
	"application/ld+json" |
	"application/msword" |
	"application/octet-stream" |
	"application/ogg" |
	"application/pdf" |
	"application/rtf" |
	"application/vnd.amazon.ebook" |
	"application/vnd.apple.installer+xml" |
	"application/vnd.mozilla.xul+xml" |
	"application/vnd.ms-excel" |
	"application/vnd.ms-fontobject" |
	"application/vnd.ms-powerpoint" |
	"application/vnd.oasis.opendocument.presentation" |
	"application/vnd.oasis.opendocument.spreadsheet" |
	"application/vnd.oasis.opendocument.text" |
	"application/vnd.openxmlformats-officedocument.presentationml.presentation" |
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" |
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document" |
	"application/vnd.rar" |
	"application/vnd.visio" |
	"application/wasm" |
	"application/x-7z-compressed" |
	"application/x-abiword" |
	"application/x-bzip" |
	"application/x-bzip2" |
	"application/x-cdf" |
	"application/x-csh" |
	"application/x-freearc" |
	"application/x-httpd-php" |
	"application/x-sh" |
	"application/x-tar" |
	"application/xhtml+xml" |
	"application/xml" |
	"application/zip" |
	"audio/aac" |
	"audio/midi" |
	"audio/mpeg" |
	"audio/ogg" |
	"audio/opus" |
	"audio/wav" |
	"audio/webm" |
	"font/otf" |
	"font/ttf" |
	"font/woff" |
	"font/woff2" |
	"image/avif" |
	"image/bmp" |
	"image/gif" |
	"image/jpeg" |
	"image/png" |
	"image/svg+xml" |
	"image/tiff" |
	"image/vnd.microsoft.icon" |
	"image/webp" |
	"text/calendar" |
	"text/css" |
	"text/csv" |
	"text/html" |
	"text/plain" |
	"video/3gpp" |
	"video/3gpp2" |
	"video/mp2t" |
	"video/mp4" |
	"video/mpeg" |
	"video/ogg" |
	"video/webm" |
	"video/x-msvideo" 
)

// END